### PR TITLE
Implement press and rotate

### PR DESCRIPTION
**Pull request by emanuelen5**
This PR is based on #51. So it needs to be merged first.

### CODE REVIEW

**Comment by nperozzi** [comment]
Do you want me to start taking a look at this PR too?

**Comment by emanuelen5** [comment]
> Do you want me to start taking a look at this PR too?

Yes, now you can take a look!

**Review by nperozzi — DISMISSED** [review]
Code looks good. 
I think I have a better understanding of function pointers and how are they used for callbacks.

**Review by nperozzi — APPROVED** [review]

**Comment by nperozzi** [comment]
I approved but it is still not letting me merge.

**Comment by emanuelen5** [comment]
^ I fixed the merge conflict by rebasing

**Pull request merged**
