### PR TITLE
SPI interrupt

### PR DESCRIPTION
**Pull request by nperozzi**
So, the ideas was the following:
1. Create the ISR for SPI
2. Modify the ´void max72xx_send_commands(max72xx_cmd_t *cmds, uint8_t length)´ to send the first byte, thus triggering the sequence of SPI interrupts that would send all the other bytes.

The main problem that I was having was that the SPI library needed to access variables and functions defined and used in the matrix72xx library. To solve this I created a struct called ´SPI_context_t´ and I made a global variable of that type, called `spi_cmds`. Then I included the max72xx library in the SPI library (generating a circular dependency 💔) and had to define `spi_cmds` as extern so it does not generate multiple definitions.

Honestly, I am unsure if this is the right way of doing it. I got to a point where I am very confused. Looking forward to hearing your thoughts. Maybe we can go through the right way of doing this on Tuesday 14th.

### CODE REVIEW

**Comment by nperozzi** [comment]
While checking your "Implement press and rotation" PR, I think that, in my SPI Interrupt implementation, I could pass `deactivate_cs()` as a callback to the SPI ISR. Would that work?
I would still need to pass the SPI_context_t "spi_cmds" somehow.

**Comment by emanuelen5** [comment]
Here is how I would probably do it:
1. Update the `SPI init` function to take the number of bytes that should be sent to the downstream devices (in our case it will be 8 bytes, since we have 4 devices that take 2 bytes each)
2. Add an interrupt queue to the SPI driver that has a capacity of 64 bytes (the data needed to update the whole display).
3. Update the SPI driver to only send data from the queue
4. The SPI driver should start sending when it has enough data to fill the downstream devices (=> 8 bytes, in our case).
5. When the driver start the transaction it should `activate_cs` and when the driver has sent 8 data it should trigger `deactivate_cs`.
6. Defensive programming: We should include an assertion, such as resetting the queue in the SPI driver before starting a new transaction, to ensure it stays in sync and prevent issues caused by application errors. Alternatively, we could add an assertion at the beginning of the transaction to verify that the data size is a multiple of 8.

**Comment by nperozzi** [comment]
Thank you. I will give it a go as soon as I am done with the mechanical design.

**Comment by nperozzi** [comment]
I am closing this PR since we seem to have a better chance to solve the SPI interrupt and SPI queue implementation in the 'SPI Interrupt 3rd attempt' PR.

**Comment by nperozzi** [comment]
I am closing this PR since we seem to have a better chance to solve the SPI interrupt and SPI queue implementation in the 'SPI Interrupt 3rd attempt' PR.

**Pull request closed without merging**
